### ISSUE TITLE
Please update version of Node.js 16 to 20.

### ISSUE THREAD

**Issue by nsalfos** [kubeshop/monokle-action#5]
Github is finally deprecating versions older than Node20. 
At this moment latest version of monokle-action v0.3.2 its still using Node16.

**Comment by nsalfos** [comment]
Tried email, discord and this, but not getting any response through any of the methods.
is there no concern about the deprecation of node16?

**Comment by olensmar** [comment]
Hi @nsalfos - sorry for the delay - looking into this now !

**Comment by WitoDelnat** [comment]
Hello @nsalfos, v0.3.3 has just been released and all deprecation notices are gone now 🎉

**Comment by nsalfos** [comment]
Thank you so much @WitoDelnat @olensmar 🙏🏼
